### ISSUE TITLE
Google Assistant SDK Not Working

### ISSUE THREAD

**Issue by guarddog13** [m50/ha-fallback-conversation#1]
I am trying this with Google Assistant SDK and get an Error Response using it as both primary and fallback. OpenAI works just fine with it.

**Comment by mclardy-godaddy** [comment]
Could you enable debug and provide me the error?

**Comment by guarddog13** [comment]
I believe it's because of the way SDK responds. It won't respond via automations either. I've moved on to Hugging Chat as its much better. On another note is there anyway we can customize "Home assistant responded with" or have the ability to turn that off completely?

**Comment by mclardy-godaddy** [comment]
The "Home assistant responded with" comes from your debug level. It will turn off if you set your debug level to "No Debug".

The purpose of it is to verify which conversation agent answered.

As for the way the SDK responds, I'm confused, if it's a conversation agent, surely it should respond the same? But glad Hugging Chat is working out for you.

**Comment by WizardCM** [comment]
I can confirm Google Assistant SDK doesn't work. Here's the stack trace:

```
2024-03-05 10:11:19.799 ERROR (MainThread) [homeassistant.components.assist_pipeline.pipeline] Unexpected error during intent recognition
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 988, in recognize_intent
    conversation_result = await conversation.async_converse(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/conversation/__init__.py", line 543, in async_converse
    result = await agent.async_process(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fallback_conversation/__init__.py", line 82, in async_process
    result = await self._async_process_agent(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fallback_conversation/__init__.py", line 128, in _async_process_agent
    result = await agent.async_process(user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/google_assistant_sdk/__init__.py", line 171, in async_process
    resp = self.assistant.assist(user_input.text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/gassist_text/textinput.py", line 119, in assist
    for resp in self.assistant.Assist(iter_assist_requests(),
  File "/usr/local/lib/python3.12/site-packages/grpc/_channel.py", line 541, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/grpc/_channel.py", line 967, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "Invalid 'dialog_state_in': unsupported language_code."
	debug_error_string = "UNKNOWN:Error received from peer <ip> {grpc_message:"Invalid \'dialog_state_in\': unsupported language_code.", grpc_status:3, created_time:"2024-03-05T10:11:19.797233017+11:00"}"
>
```

I'm assuming the configured language code isn't being forwarded:

![image](https://github.com/m50/ha-fallback-conversation/assets/941350/d30fda2f-095d-4ede-9d38-ad624fcac503)

**Comment by t0bst4r** [comment]
I have two more ideas, what could happen here.

1. does google assistant support en-AU? Could you try the whole setup with en-US?

2. does it support language codes at all? For open ai, it has "*" configured as supported language - you don’t get a language dropdown when configuring it. Anyway, the fallback integration forwards the language code to the google integration, but it is ignored by OpenAI. Does the google assistant integration doesn’t ignore it, but validates it?

**Comment by WizardCM** [comment]
`en-AU` is supported, it's listed in the dropdown:
![image](https://github.com/m50/ha-fallback-conversation/assets/941350/32608c69-2e9f-455d-a6cf-a5587eb02a5c)

Changing the dropdown to `en-US` did not fix it. Same error:

```
2024-03-07 13:36:13.545 ERROR (MainThread) [homeassistant.components.assist_pipeline.pipeline] Unexpected error during intent recognition
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 992, in recognize_intent
conversation_result = await conversation.async_converse(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/conversation/__init__.py", line 543, in async_converse
result = await agent.async_process(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/fallback_conversation/__init__.py", line 82, in async_process
result = await self._async_process_agent(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/fallback_conversation/__init__.py", line 128, in _async_process_agent
result = await agent.async_process(user_input)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/google_assistant_sdk/__init__.py", line 171, in async_process
resp = self.assistant.assist(user_input.text)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/gassist_text/textinput.py", line 119, in assist
for resp in self.assistant.Assist(iter_assist_requests(),
File "/usr/local/lib/python3.12/site-packages/grpc/_channel.py", line 541, in __next__
return self._next()
^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/grpc/_channel.py", line 967, in _next
raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
status = StatusCode.INVALID_ARGUMENT
details = "Invalid 'dialog_state_in': unsupported language_code."
debug_error_string = "UNKNOWN:Error received from peer ipv6:ip:443 {grpc_message:"Invalid \'dialog_state_in\': unsupported language_code.", grpc_status:3, created_time:"2024-03-07T13:36:13.544037995+11:00"}"
```

For reference, this is the UI flow:

https://github.com/m50/ha-fallback-conversation/assets/941350/1f9a7ec7-2b96-4a11-af13-8d9f1c724e00

It does not matter if Google Assistant SDK is in the Primary or Fallback slot, both provide the same error.

**Comment by t0bst4r** [comment]
Okay, this seems to be an error coming from the google assistant sdk. (see https://github.com/googlesamples/assistant-sdk-python/issues/172)

But since `en-AU` is definitely supported (see https://developers.google.com/assistant/sdk/reference/rpc/languages), it could be that this fallback integration does not pass the language code correctly. We would need some further investigation.

**Comment by t0bst4r** [comment]
@WizardCM 

I just had a deeper look at how languages work in conversation agents, and it seems to be a problem with language selection of home assistant in general.

### Root Cause

- When creating your assist configuration a language is selected:
![Screenshot 07 03 2024 um 10 14 25 AM](https://github.com/m50/ha-fallback-conversation/assets/82281152/1987dd46-9257-4360-9ac1-20dd75db2f60)

- This language is not using the pattern `en-US` or something. It is just `en`.

- In the next step, you configure your conversation agent. There you can select the specific dialect, if available. For German, you can select between `de` and `de-CH` (note that it's still not `de-DE`).
![Screenshot 07 03 2024 um 10 17 07 AM](https://github.com/m50/ha-fallback-conversation/assets/82281152/6ec68eb1-55c0-4869-9b5d-dbcb9458197a)

- For english there is only `en` available:
![Screenshot 07 03 2024 um 10 17 48 AM](https://github.com/m50/ha-fallback-conversation/assets/82281152/2a9e2c2c-f51e-45fa-83ef-77606151a9b1)
(see: https://github.com/home-assistant/intents-package/blob/77889c04abd9c6c8b1fab3e457a3aeee1cb681bc/home_assistant_intents/languages.py)

- The selected language is then passed to the configured conversation agent (in my case it's the fallback agent).

- The fallback agent then calls the primary and secondary agents if neccessary and passes through the configured assist language.

- **yes**, you configure your own language at the Google Assistant SDK agent, but I've had a look at the code - **it is ignored**. The language you configure at the Google Agent is just the `default` language, which is used, when **no** language is provided (e.g. in a service call, or when you make it the ONLY agent). But in combination with the fallback agent, where the language is passed in from Assist, it will not use the configured default, but it will use the language from assist.

### Conclusion
Languages supported by Home Assistant's Assist and those supported by Google Assistant SDK are not compatible. Additionally Google Assistant SDK Integration does have a mechanism to find the best matching language, but it does not use this mechanism in its agent, but only for different services.

**It is a bug in the Google Assistant SDK integration.**


### Possible Solutions

Bugfix in the Google Assistant SDK Integration to check, if the selected language is supported. And if not, try to find the best matching language.

Just one idea, of how i would fix that. I will raise a merge request for that in home assistant core:
(Pseudo-Code)
```
[ 1 ] if user_input.language in SUPPORTED_LANGUAGES:
[ 2 ]   return user_input.language
[ 3 ] lang_code = user_input.language.split("-")[0]
[ 4 ] if configured_language.startswith(lang_code):
[ 5 ]   return configured_language
[ 6 ] google_default_lang = DEFAULT_LANGUAGE_CODES.get(lang_code)
[ 7 ] if google_default_lang is not None:
[ 8 ]   return google_default_lang
[ 9 ] return default_language_code(hass)
```

**Test Cases**

1. If assist language is `en` line 1 will return false.
But since you have configured `en-AU` as your Google Assistant Language, it should return `en-AU` in line 5.

2. If assist language is `en-XYZ` line 1 will return false.
But since you have configured `en-AU` as your Google Assistant Language, it should return `en-AU` in line 5.

3. If assist language is `de-DE` line 1 will return true. It will be used.

4. If assist language is `de-XYZ` line 1 will return false.
Since you have configured `en-AU` as your Google Assistant Language, it should return false in line 4.
It will split the language code and find the default language for `de`, which will return `de-DE` in line 8

4. If assist language is `abc-XYZ` line 1 will return false.
Since you have configured `en-AU` as your Google Assistant Language, it should return false in line 4.
It will split the language code and tries to find the default language for `abc`. Since there is no language like `abc`, it will use the built-in mechanism to fallback to your home assistant default language.


@m50: just for your interest 😄 
I'd expect similar bugs in other conversation agents in the future.

**Comment by t0bst4r** [comment]
I have created a pull request in home assistant:

https://github.com/home-assistant/core/pull/112600

**Comment by t0bst4r** [comment]
@guarddog13 @WizardCM @mclardy-godaddy 
I don't know, why it took so long, but finally the pull request was merged 🎉
